from tap_youtube_analytics.streams.channels import Channels
from tap_youtube_analytics.streams.playlists import Playlists
from tap_youtube_analytics.streams.playlist_items import PlaylistItems
from tap_youtube_analytics.streams.videos import Videos
from tap_youtube_analytics.streams.reports import (ChannelBasicStream, ChannelProvinceStream, 
                                                   ChannelPlaybackLocationStream, 
                                                   ChannelTrafficSourceStream, 
                                                   ChannelDeviceOSStream, ChannelDemographicsStream, 
                                                   ChannelSharingServiceStream, 
                                                   ChannelAnnotationsStream, ChannelCardsStream, 
                                                   ChannelEndScreensStream, ChannelSubtitlesStream, 
                                                   ChannelCombinedStream, PlaylistBasicStream, 
                                                   PlaylistProvinceStream, 
                                                   PlaylistPlaybackLocationStream, 
                                                   PlaylistTrafficSourceStream, 
                                                   PlaylistDeviceOSStream, 
                                                   PlaylistCombinedStream, 
                                                   ContentOwnerBasicStream, 
                                                   ContentOwnerProvinceStream, 
                                                   ContentOwnerPlaybackLocationStream, 
                                                   ContentOwnerTrafficSourceStream, 
                                                   ContentOwnerDeviceOSStream, 
                                                   ContentOwnerDemographicsStream, 
                                                   ContentOwnerSharingServiceStream, 
                                                   ContentOwnerAnnotationsStream, 
                                                   ContentOwnerCardsStream, 
                                                   ContentOwnerEndScreensStream, 
                                                   ContentOwnerSubtitlesStream, 
                                                   ContentOwnerCombinedStream, 
                                                   ContentOwnerPlaylistBasicStream, 
                                                   ContentOwnerPlaylistProvinceStream, 
                                                   ContentOwnerPlaylistPlaybackLocationStream, 
                                                   ContentOwnerPlaylistTrafficSourceStream, 
                                                   ContentOwnerPlaylistDeviceOSStream, 
                                                   ContentOwnerPlaylistCombinedStream, 
                                                   ContentOwnerAdRatesStream, 
                                                   ContentOwnerEstimatedRevenueStream, 
                                                   ContentOwnerAssetEstimatedRevenueStream, 
                                                   ContentOwnerAssetBasicStream, 
                                                   ContentOwnerAssetProvinceStream, 
                                                   ContentOwnerAssetPlaybackLocationStream, 
                                                   ContentOwnerAssetTrafficSourceStream, 
                                                   ContentOwnerAssetDeviceOSStream, 
                                                   ContentOwnerAssetDemographicsStream, 
                                                   ContentOwnerAssetSharingServiceStream, 
                                                   ContentOwnerAssetAnnotationsStream, 
                                                   ContentOwnerAssetCardsStream, 
                                                   ContentOwnerAssetEndScreensStream, 
                                                   ContentOwnerAssetCombinedStream)

STREAMS = {
    "channels": Channels,
    "playlists": Playlists,
    "playlist_items": PlaylistItems,
    "videos": Videos,
    "channel_basic": ChannelBasicStream,
    "channel_province": ChannelProvinceStream,
    "channel_playback_location": ChannelPlaybackLocationStream,
    "channel_traffic_source": ChannelTrafficSourceStream,
    "channel_device_os": ChannelDeviceOSStream,
    "channel_demographics": ChannelDemographicsStream,
    "channel_sharing_service": ChannelSharingServiceStream,
    "channel_annotations": ChannelAnnotationsStream,
    "channel_cards": ChannelCardsStream,
    "channel_end_screens": ChannelEndScreensStream,
    "channel_subtitles": ChannelSubtitlesStream,
    "channel_combined": ChannelCombinedStream,
    "playlist_basic": PlaylistBasicStream,
    "playlist_province": PlaylistProvinceStream,
    "playlist_playback_location": PlaylistPlaybackLocationStream,
    "playlist_traffic_source": PlaylistTrafficSourceStream,
    "playlist_device_os": PlaylistDeviceOSStream,
    "playlist_combined": PlaylistCombinedStream,
    "content_owner_basic": ContentOwnerBasicStream,
    "content_owner_province": ContentOwnerProvinceStream,
    "content_owner_playback_location": ContentOwnerPlaybackLocationStream,
    "content_owner_traffic_source": ContentOwnerTrafficSourceStream,
    "content_owner_device_os": ContentOwnerDeviceOSStream,
    "content_owner_demographics": ContentOwnerDemographicsStream,
    "content_owner_sharing_service": ContentOwnerSharingServiceStream,
    "content_owner_annotations": ContentOwnerAnnotationsStream,
    "content_owner_cards": ContentOwnerCardsStream,
    "content_owner_end_screens": ContentOwnerEndScreensStream,
    "content_owner_subtitles": ContentOwnerSubtitlesStream,
    "content_owner_combined": ContentOwnerCombinedStream,
    "content_owner_playlist_basic": ContentOwnerPlaylistBasicStream,
    "content_owner_playlist_province": ContentOwnerPlaylistProvinceStream,
    "content_owner_playlist_playback_location": ContentOwnerPlaylistPlaybackLocationStream,
    "content_owner_playlist_traffic_source": ContentOwnerPlaylistTrafficSourceStream,
    "content_owner_playlist_device_os": ContentOwnerPlaylistDeviceOSStream,
    "content_owner_playlist_combined": ContentOwnerPlaylistCombinedStream,
    "content_owner_ad_rates": ContentOwnerAdRatesStream,
    "content_owner_estimated_revenue": ContentOwnerEstimatedRevenueStream,
    "content_owner_asset_estimated_revenue": ContentOwnerAssetEstimatedRevenueStream,
    "content_owner_asset_basic": ContentOwnerAssetBasicStream,
    "content_owner_asset_province": ContentOwnerAssetProvinceStream,
    "content_owner_asset_playback_location": ContentOwnerAssetPlaybackLocationStream,
    "content_owner_asset_traffic_source": ContentOwnerAssetTrafficSourceStream,
    "content_owner_asset_device_os": ContentOwnerAssetDeviceOSStream,
    "content_owner_asset_demographics": ContentOwnerAssetDemographicsStream,
    "content_owner_asset_sharing_service": ContentOwnerAssetSharingServiceStream,
    "content_owner_asset_annotations": ContentOwnerAssetAnnotationsStream,
    "content_owner_asset_cards": ContentOwnerAssetCardsStream,
    "content_owner_asset_end_screens": ContentOwnerAssetEndScreensStream,
    "content_owner_asset_combined": ContentOwnerAssetCombinedStream
}