from tap_youtube_analytics.streams.channels import Channels
from tap_youtube_analytics.streams.playlists import Playlists
from tap_youtube_analytics.streams.playlist_items import PlaylistItems
from tap_youtube_analytics.streams.videos import Videos
from tap_youtube_analytics.streams.reports import (ChannelBasicStream, ChannelProvinceStream, 
                                                   ChannelPlaybackLocationStream, 
                                                   ChannelTrafficSourceStream, 
                                                   ChannelDeviceOSStream, ChannelDemographicsStream, 
                                                   ChannelSharingServiceStream, 
                                                   ChannelAnnotationsStream, ChannelCardsStream, 
                                                   ChannelEndScreensStream, ChannelSubtitlesStream, 
                                                   ChannelCombinedStream, PlaylistBasicStream, 
                                                   PlaylistProvinceStream, 
                                                   PlaylistPlaybackLocationStream, 
                                                   PlaylistTrafficSourceStream, 
                                                   PlaylistDeviceOSStream, 
                                                   PlaylistCombinedStream, 
                                                   ContentOwnerBasicStream, 
                                                   ContentOwnerProvinceStream, 
                                                   ContentOwnerPlaybackLocationStream, 
                                                   ContentOwnerTrafficSourceStream, 
                                                   ContentOwnerDeviceOSStream, 
                                                   ContentOwnerDemographicsStream, 
                                                   ContentOwnerSharingServiceStream, 
                                                   ContentOwnerAnnotationsStream, 
                                                   ContentOwnerCardsStream, 
                                                   ContentOwnerEndScreensStream, 
                                                   ContentOwnerSubtitlesStream, 
                                                   ContentOwnerCombinedStream, 
                                                   ContentOwnerPlaylistBasicStream, 
                                                   ContentOwnerPlaylistProvinceStream, 
                                                   ContentOwnerPlaylistPlaybackLocationStream, 
                                                   ContentOwnerPlaylistTrafficSourceStream, 
                                                   ContentOwnerPlaylistDeviceOSStream, 
                                                   ContentOwnerPlaylistCombinedStream, 
                                                   ContentOwnerAdRatesStream, 
                                                   ContentOwnerEstimatedRevenueStream, 
                                                   ContentOwnerAssetEstimatedRevenueStream, 
                                                   ContentOwnerAssetBasicStream, 
                                                   ContentOwnerAssetProvinceStream, 
                                                   ContentOwnerAssetPlaybackLocationStream, 
                                                   ContentOwnerAssetTrafficSourceStream, 
                                                   ContentOwnerAssetDeviceOSStream, 
                                                   ContentOwnerAssetDemographicsStream, 
                                                   ContentOwnerAssetSharingServiceStream, 
                                                   ContentOwnerAssetAnnotationsStream, 
                                                   ContentOwnerAssetCardsStream, 
                                                   ContentOwnerAssetEndScreensStream, 
                                                   ContentOwnerAssetCombinedStream)

STREAMS = {
    "channels": Channels,
    "playlists": Playlists,
    "playlist_items": PlaylistItems,
    "videos": Videos,
    "channel_basic_a3": ChannelBasicStream,
    "channel_province_a3": ChannelProvinceStream,
    "channel_playback_location_a3": ChannelPlaybackLocationStream,
    "channel_traffic_source_a3": ChannelTrafficSourceStream,
    "channel_device_os_a3": ChannelDeviceOSStream,
    "channel_demographics_a1": ChannelDemographicsStream,
    "channel_sharing_service_a2": ChannelSharingServiceStream,
    "channel_annotations_a2": ChannelAnnotationsStream,
    "channel_cards_a2": ChannelCardsStream,
    "channel_end_screens_a2": ChannelEndScreensStream,
    "channel_subtitles_a3": ChannelSubtitlesStream,
    "channel_combined_a3": ChannelCombinedStream,
    "playlist_basic_a2": PlaylistBasicStream,
    "playlist_province_a2": PlaylistProvinceStream,
    "playlist_playback_location_a2": PlaylistPlaybackLocationStream,
    "playlist_traffic_source_a2": PlaylistTrafficSourceStream,
    "playlist_device_os_a2": PlaylistDeviceOSStream,
    "playlist_combined_a2": PlaylistCombinedStream,
    "content_owner_basic_a4": ContentOwnerBasicStream,
    "content_owner_province_a3": ContentOwnerProvinceStream,
    "content_owner_playback_location_a3": ContentOwnerPlaybackLocationStream,
    "content_owner_traffic_source_a3": ContentOwnerTrafficSourceStream,
    "content_owner_device_os_a3": ContentOwnerDeviceOSStream,
    "content_owner_demographics_a1": ContentOwnerDemographicsStream,
    "content_owner_sharing_service_a1": ContentOwnerSharingServiceStream,
    "content_owner_annotations_a1": ContentOwnerAnnotationsStream,
    "content_owner_cards_a1": ContentOwnerCardsStream,
    "content_owner_end_screens_a1": ContentOwnerEndScreensStream,
    "content_owner_subtitles_a3": ContentOwnerSubtitlesStream,
    "content_owner_combined_a3": ContentOwnerCombinedStream,
    "content_owner_playlist_basic_a2": ContentOwnerPlaylistBasicStream,
    "content_owner_playlist_province_a2": ContentOwnerPlaylistProvinceStream,
    "content_owner_playlist_playback_location_a2": ContentOwnerPlaylistPlaybackLocationStream,
    "content_owner_playlist_traffic_source_a2": ContentOwnerPlaylistTrafficSourceStream,
    "content_owner_playlist_device_os_a2": ContentOwnerPlaylistDeviceOSStream,
    "content_owner_playlist_combined_a2": ContentOwnerPlaylistCombinedStream,
    "content_owner_ad_rates_a1": ContentOwnerAdRatesStream,
    "content_owner_estimated_revenue_a2": ContentOwnerEstimatedRevenueStream,
    "content_owner_asset_estimated_revenue_a2": ContentOwnerAssetEstimatedRevenueStream,
    "content_owner_asset_basic_a3": ContentOwnerAssetBasicStream,
    "content_owner_asset_province_a3": ContentOwnerAssetProvinceStream,
    "content_owner_asset_playback_location_a3": ContentOwnerAssetPlaybackLocationStream,
    "content_owner_asset_traffic_source_a3": ContentOwnerAssetTrafficSourceStream,
    "content_owner_asset_device_os_a3": ContentOwnerAssetDeviceOSStream,
    "content_owner_asset_demographics_a1": ContentOwnerAssetDemographicsStream,
    "content_owner_asset_sharing_service_a1": ContentOwnerAssetSharingServiceStream,
    "content_owner_asset_annotations_a1": ContentOwnerAssetAnnotationsStream,
    "content_owner_asset_cards_a1": ContentOwnerAssetCardsStream,
    "content_owner_asset_end_screens_a1": ContentOwnerAssetEndScreensStream,
    "content_owner_asset_combined_a3": ContentOwnerAssetCombinedStream
}
