def config():
    return {
        "test_name": "test_sync_non_report_streams",
        "tap_name": "tap-youtube-analytics",
        "type": "platform.youtube-analytics",
        "properties": {
            "channel_ids": "TAP_YOUTUBE_ANALYTICS_CHANNEL_IDS",
            "start_date": "TAP_YOUTUBE_ANALYTICS_START_DATE"
        },
        "credentials": {
            "client_id": "TAP_YOUTUBE_ANALYTICS_CLIENT_ID",
            "client_secret": "TAP_YOUTUBE_ANALYTICS_CLIENT_SECRET",
            "refresh_token": "TAP_YOUTUBE_ANALYTICS_REFRESH_TOKEN",
        },
        "bookmark": {
            "bookmark_key": "playlist_items",
            "bookmark_timestamp": "2020-12-01T15:10:32.000000Z"
        },
        "streams": {
            "channels": {"id"},
            "playlists": {"id"},
            "playlist_items": {"id"},
            "videos": {"id"},
            "channel_basic": {"report_id"},
            "channel_province": {"report_id"},
            "channel_playback_location": {"report_id"},
            "channel_traffic_source": {"report_id"},
            "channel_device_os": {"report_id"},
            "channel_demographics": {"report_id"},
            "channel_sharing_service": {"report_id"},
            "channel_annotations": {"report_id"},
            "channel_cards": {"report_id"},
            "channel_end_screens": {"report_id"},
            "channel_subtitles": {"report_id"},
            "channel_combined": {"report_id"},
            "playlist_basic": {"report_id"},
            "playlist_province": {"report_id"},
            "playlist_playback_location": {"report_id"},
            "playlist_traffic_source": {"report_id"},
            "playlist_device_os": {"report_id"},
            "playlist_combined": {"report_id"},
            "content_owner_basic": {"report_id"},
            "content_owner_province": {"report_id"},
            "content_owner_playback_location": {"report_id"},
            "content_owner_traffic_source": {"report_id"},
            "content_owner_device_os": {"report_id"},
            "content_owner_demographics": {"report_id"},
            "content_owner_annotations": {"report_id"},
            "content_owner_cards": {"report_id"},
            "content_owner_end_screens": {"report_id"},
            "content_owner_subtitles": {"report_id"},
            "content_owner_combined": {"report_id"},
            "content_owner_playlist_basic": {"report_id"},
            "content_owner_playlist_province": {"report_id"},
            "content_owner_playlist_playback_location": {"report_id"},
            "content_owner_playlist_traffic_source": {"report_id"},
            "content_owner_playlist_device_os": {"report_id"},
            "content_owner_playlist_combined": {"report_id"},
            "content_owner_ad_rates": {"report_id"},
            "content_owner_estimated_revenue": {"report_id"},
            "content_owner_asset_estimated_revenue": {"report_id"},
            "content_owner_asset_basic": {"report_id"},
            "content_owner_asset_province": {"report_id"},
            "content_owner_asset_playback_location": {"report_id"},
            "content_owner_asset_traffic_source": {"report_id"},
            "content_owner_asset_device_os": {"report_id"},
            "content_owner_asset_demographics": {"report_id"},
            "content_owner_asset_sharing_service": {"report_id"},
            "content_owner_asset_annotations": {"report_id"},
            "content_owner_asset_cards": {"report_id"},
            "content_owner_asset_end_screens": {"report_id"},
            "content_owner_asset_combined": {"report_id"}
        },
        "exclude_streams": ["channel_traffic_source",
                            "channel_demographics",
                            "channel_sharing_service",
                            "channel_annotations",
                            "channel_cards",
                            "channel_end_screens",
                            "playlist_basic",
                            "playlist_province",
                            "playlist_playback_location",
                            "playlist_traffic_source",
                            "playlist_device_os",
                            "playlist_combined",
                            "content_owner_basic",
                            "content_owner_province",
                            "content_owner_playback_location",
                            "content_owner_traffic_source",
                            "content_owner_device_os",
                            "content_owner_demographics",
                            "content_owner_annotations",
                            "content_owner_cards",
                            "content_owner_end_screens",
                            "content_owner_subtitles",
                            "content_owner_combined",
                            "content_owner_playlist_basic",
                            "content_owner_playlist_province",
                            "content_owner_playlist_playback_location",
                            "content_owner_playlist_traffic_source",
                            "content_owner_playlist_device_os",
                            "content_owner_playlist_combined",
                            "content_owner_ad_rates",
                            "content_owner_estimated_revenue",
                            "content_owner_asset_estimated_revenue",
                            "content_owner_asset_basic",
                            "content_owner_asset_province",
                            "content_owner_asset_playback_location",
                            "content_owner_asset_traffic_source",
                            "content_owner_asset_device_os",
                            "content_owner_asset_demographics",
                            "content_owner_asset_sharing_service",
                            "content_owner_asset_annotations",
                            "content_owner_asset_cards",
                            "content_owner_asset_end_screens",
                            "content_owner_asset_combined"]
    }
